### ISSUE TITLE
Can read multiple model/blueprint

### ISSUE THREAD

**Issue by bhangun** [bhangun/golok#1]
Can read multiple model/blueprint and merge it in one model.
Main model should like this  :
```
includes:
  - file: example/product.yaml
    entities: Product
    enums: Unit
  - file: example/order.yaml
```
by default it would merge all attribute define in file, instead merge as define.
